pipeline_name: customers
owner: customer_success
source:
  type: csv
  path: data_sources/customers.csv
destination:
  schema: raw
  table: customers
schedule:
  cron: "0 */6 * * *"
load_mode: append
runtime_parameters:
  batch_size: 1000
transform: {}
